x-logging: &logging {}

x-json-logging:
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "10"

services:
  erigon:
    image: thorax/erigon:${IMAGE_TAG:-latest}
    restart: unless-stopped
    volumes:
      - ${ERIGON_DATADIR}:/data
    stop_grace_period: 2m
    healthcheck:
      test: ["CMD-SHELL", "true"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --internalcl
      - --chain=${CHAIN}
      - --datadir=/data
      - --nat=pmp:${NAT_PMP_GATEWAY}
      - --http.api=eth,net,web3,erigon,engine
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --log.console.verbosity=${LOG_VERBOSITY}
      - --sentry.log-peer-info
      - --metrics
    <<: *logging
